name: third Workflow
on:
  push:
    branches:
      - main
      - master
env:
  MY_NAME: 'Sindhu' >> arti.txt

jobs:
  this-is-03-first-job:
    name: GH-03-01-job
    runs-on: ubuntu-latest
    env:
      MY_NIECE: 'Kuttu' 
    steps:
      
      - name: printing my name     
        run: |
           echo "MY_NAME=$MY_NAME" > arti.txt
           echo "MY_NIECE=$MY_NIECE" >> arti.txt
           echo "MY_OFF=$MY_OFF" >> arti.txt
      - name: printing my office name
        env:
          MY_OFF: 'Aspire system'
        run: echo "my off is $MY_OFF" 

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: arti.txt

  this-is-03-second-job:
    name: GH-03-02-job
    runs-on: ubuntu-latest
    needs: this-is-03-first-job
    steps:
      
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: .
      - name: name from first job
        run: |
           echo "My name is $MY_NAME"
           echo "$MY_NIECE"
           echo "$MY_OFF"

  


