name: third Workflow
on:
  push:
    branches:
      - main
      - master
env:
  MY_NAME: 'Sindhu'

jobs:
  this-is-03-first-job:
    name: GH-03-01-job
    runs-on: ubuntu-latest
    env:
      MY_NIECE: 'Kuttu'
    steps:
      
      - name: printing my name     
        run: |
           echo "hello $MY_NAME"
           echo "hello $MY_NIECE"
      - name: printing my office name
        env:
          MY_OFF: 'Aspire system'
        run: echo "my off is $MY_OFF"
  this-is-03-second-job:
    name: GH-03-02-job
    runs-on: ubuntu-latest
    steps:
      - name: name from first job
        run: |
           echo "My name is $MY_NAME"
           echo "$MY_NIECE"
           echo "$MY_OFF"

  


