name: third Workflow
on:
  push:
    branches:
      - main
      - master
jobs:
  this is 03 first job:
    name: GH-03-01-job
    runs-on: ubuntu-latest
    steps:
      name: printing my name 
      run: |
           echo "hello sindhu"
           echo "hello kuttu"
    steps:
      name: printing my office name
      run: echo "Aspire system"
